import { motion } from 'framer-motion';
import { FileText, CheckCircle, AlertTriangle, Scale, UserX, Shield } from 'lucide-react';

export default function Terms() {
  const sections = [
    {
      icon: CheckCircle,
      title: 'Acceptance of Terms',
      content: `By accessing and using AI Super Hub, you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform.

These terms apply to all users, including visitors, registered users, and premium subscribers.`
    },
    {
      icon: UserX,
      title: 'User Accounts',
      content: `Account Registration:
• You must provide accurate and complete information
• You are responsible for maintaining account security
• You must be at least 13 years old to create an account
• One person may not maintain multiple accounts

Account Termination:
• You may delete your account at any time from Settings
• We reserve the right to suspend or terminate accounts that violate our terms
• We will provide notice before termination when possible`
    },
    {
      icon: Scale,
      title: 'Acceptable Use',
      content: `You agree NOT to:
• Use the platform for any illegal purposes
• Attempt to gain unauthorized access to our systems
• Interfere with or disrupt the platform's functionality
• Upload malicious code, viruses, or harmful content
• Harass, abuse, or harm other users
• Scrape, copy, or redistribute our content without permission
• Use our AI services to generate harmful, illegal, or inappropriate content
• Impersonate others or provide false information

Violations may result in immediate account termination.`
    },
    {
      icon: FileText,
      title: 'Intellectual Property',
      content: `Platform Content:
• All course materials, tools directory, prompts, and content are owned by AI Super Hub
• You may use our content for personal learning purposes only
• Commercial use requires written permission

User Content:
• You retain ownership of content you create using our platform
• You grant us a license to store and display your content as necessary to provide our services
• You are responsible for ensuring you have rights to any content you upload`
    },
    {
      icon: Shield,
      title: 'AI Services & Limitations',
      content: `AI Chat & Features:
• AI responses are generated by third-party AI models (Google Gemini)
• We do not guarantee accuracy, completeness, or reliability of AI-generated content
• AI responses should not be considered professional advice
• You are responsible for verifying AI-generated information
• We reserve the right to monitor AI usage to prevent abuse

Service Limitations:
• We do not guarantee uninterrupted or error-free service
• We may modify, suspend, or discontinue features at any time
• Usage limits may apply to prevent abuse`
    },
    {
      icon: AlertTriangle,
      title: 'Disclaimers & Liability',
      content: `Disclaimer of Warranties:
• Our platform is provided "as is" without warranties of any kind
• We do not guarantee specific outcomes from using our courses or tools
• AI-generated content may contain errors or inaccuracies

Limitation of Liability:
• We are not liable for any indirect, incidental, or consequential damages
• Our total liability is limited to the amount you paid for services (if any)
• Some jurisdictions do not allow liability limitations, so these may not apply to you

Educational Purpose:
• Our courses and content are for educational purposes only
• They do not constitute professional certification or accreditation
• Certificates earned are issued by AI Super Hub, not external accrediting bodies`
    },
  ];

  return (
    <div className="min-h-screen pt-24 pb-12" style={{ backgroundColor: 'var(--color-bg)' }}>
      <div className="container-custom max-w-4xl">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-16"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-500/10 border border-blue-500/20 text-blue-400 text-sm mb-6">
            <FileText className="w-4 h-4" />
            Terms of Service
          </div>
          
          <h1 className="text-4xl md:text-5xl font-bold mb-6" style={{ color: 'var(--color-text)' }}>
            Terms of Service
          </h1>
          
          <p className="text-lg max-w-2xl mx-auto" style={{ color: 'var(--color-text-secondary)' }}>
            Please read these terms carefully before using AI Super Hub. By using our platform, 
            you agree to be bound by these terms.
          </p>
          
          <p className="text-sm mt-4" style={{ color: 'var(--color-text-muted)' }}>
            Last updated: December 8, 2024
          </p>
        </motion.div>

        {/* Terms Sections */}
        <div className="space-y-6">
          {sections.map((section, index) => {
            const Icon = section.icon;
            return (
              <motion.div
                key={section.title}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="card"
              >
                <div className="flex items-start gap-4 mb-4">
                  <div 
                    className="w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0"
                    style={{ backgroundColor: 'rgba(79,195,247,0.1)' }}
                  >
                    <Icon className="w-6 h-6" style={{ color: 'var(--color-secondary)' }} />
                  </div>
                  <div className="flex-1">
                    <h2 className="text-xl font-bold mb-3" style={{ color: 'var(--color-text)' }}>
                      {section.title}
                    </h2>
                    <div 
                      className="prose prose-sm max-w-none whitespace-pre-line leading-relaxed"
                      style={{ color: 'var(--color-text-secondary)' }}
                    >
                      {section.content}
                    </div>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>

        {/* Changes Section */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.8 }}
          className="card mt-12"
        >
          <h2 className="text-xl font-bold mb-3" style={{ color: 'var(--color-text)' }}>
            Changes to Terms
          </h2>
          <p style={{ color: 'var(--color-text-secondary)' }}>
            We may update these Terms of Service from time to time. We will notify users of any material 
            changes via email or through a notice on our platform. Continued use of AI Super Hub after 
            changes constitutes acceptance of the updated terms.
          </p>
        </motion.div>

        {/* Contact */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.9 }}
          className="card mt-6 text-center"
        >
          <h2 className="text-xl font-bold mb-3" style={{ color: 'var(--color-text)' }}>
            Questions?
          </h2>
          <p className="mb-4" style={{ color: 'var(--color-text-secondary)' }}>
            If you have questions about these Terms, please contact us at:
          </p>
          <a 
            href="mailto:legal@aisuperhub.com"
            className="text-[var(--color-primary)] hover:underline font-medium"
          >
            legal@aisuperhub.com
          </a>
        </motion.div>
      </div>
    </div>
  );
}
